### ISSUE TITLE
last enroll ack is not necessary

### ISSUE THREAD

**Issue by fedy0** [francis94c/protocols#4]
Last packet in enroll (ie ack) is not necessary. If the application does fails to get the enrolled template, then let it prompt the user about the failed capture and to request again (with the same command explained above in the same file).

**Comment by francis94c** [comment]
the module is meant to prompt the user for a failed capture using the lcd packet. the android device never closes the connection once it begins the request for a template until it sends that particular ack packet for a template packet and only for a template packet. sending of a template packet ends the business transaction... if the enrollment was unsuccessful, use the lcd packet to indicate that because the app is still listening for response and will keep listening till it gets a template.  like the song "I will never let you go, unless you bless me, i will never let you go, unless u bless me".
